version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: "circleci/node:4.8.2"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-cache search openjdk-7
      - run: sudo apt-get -y install openjdk-7
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: mkdir junit
      - run: ./node_modules/wdio/node_modules/.bin/wdio wdio.conf.js
      - store_test_results:
          path: junit
      - store_artifacts:
          path: errorShots
          destination: errorShots
      - run: "curl -f -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/load-test/tree/master"
